/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import auto.InputDataController;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gorz
 */
public class CarInfo extends javax.swing.JFrame implements Clearable {

    private GuiController controller;
    private InputDataController inputDataController;
    
    /**
     * Creates new form CarInfo
     */
    public CarInfo(GuiController controller, InputDataController inputDataController) {
        initComponents();
        this.controller = controller;
        this.inputDataController = inputDataController;
        ArrayList<String> brands = inputDataController.getBrands();
        brand.removeAllItems();
        for(String n : brands) {
            brand.addItem(n);
        }
        brand.setSelectedIndex(0);
        ArrayList<String> bodies = inputDataController.getBodies();
        body.removeAllItems();
        for(String n : bodies) {
            body.addItem(n);
        }
        body.setSelectedIndex(0);
        //this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        brand = new javax.swing.JComboBox();
        model = new javax.swing.JComboBox();
        yearLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        volume = new javax.swing.JTextField();
        bodyLabel = new javax.swing.JLabel();
        body = new javax.swing.JComboBox();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        taxLabel = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        regionLabel = new javax.swing.JLabel();
        region = new javax.swing.JComboBox();
        massLabel = new javax.swing.JLabel();
        mass = new javax.swing.JTextField();
        mileageLable = new javax.swing.JLabel();
        mileage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Информация о машине");

        brandLabel.setText("Марка:");

        modelLabel.setText("Модель:");

        brand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brandItemStateChanged(evt);
            }
        });

        yearLabel.setText("Год выпуска:");

        volumeLabel.setText("Объем двигателя:");

        year.setText("2010");

        bodyLabel.setText("Тип кузова:");

        back.setText("Назад");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setText("Продолжить");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        taxLabel.setText("Сумма налога:");

        regionLabel.setText("Регион:");

        region.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Регионы с низким инвестиционным интересом", "Регионы с выскоим инвестиционным интересом", "Другие районы" }));

        massLabel.setText("Масса:");

        mass.setText("2.8");

        mileageLable.setText("Пробег:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(region, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regionLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(massLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mass))
                                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(mileageLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mileage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(taxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(next))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brandLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(yearLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                    .addComponent(brand, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(modelLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(volumeLabel)
                                                .addGap(4, 4, 4)
                                                .addComponent(volume))
                                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(bodyLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(modelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeLabel)
                    .addComponent(yearLabel)
                    .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bodyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(massLabel)
                    .addComponent(mileageLable)
                    .addComponent(mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(next)
                    .addComponent(taxLabel)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.changeFrame("driverInfo");
    }//GEN-LAST:event_backActionPerformed
    
    @Override
    public void clear() {
        brand.setSelectedIndex(0);
        body.setSelectedIndex(0);
        volume.setText("");
        year.setText("");
        body.setSelectedIndex(0);
        mass.setText("");
        mileage.setText("");
        region.setSelectedIndex(0);
        tax.setText("");
    }
    
    private void brandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brandItemStateChanged
        ArrayList<String> models = inputDataController.getModels(brand.getSelectedIndex());
        model.removeAllItems();
        if(models == null) {
            JOptionPane.showMessageDialog(this, "Сбой БД!");
            return;
        }
        for(String n : models) {
            model.addItem(n);
        }
    }//GEN-LAST:event_brandItemStateChanged

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        int yearVal;
        float volumeVal, taxVal, massVal, mileageVal;
        try {
            yearVal = Integer.valueOf(year.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Значение 'Год выпуска' должно быть целым числом!");
            return;
        }
        if(yearVal < 1950) {
            JOptionPane.showMessageDialog(this, "Значение 'Год выпуска' должно быть больше 1950!");
            return;
        }
        try {
            volumeVal = Float.valueOf(volume.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Значение 'Объем двигателя' должно быть числом!");
            return;
        }
        if(volumeVal <= 0) {
            JOptionPane.showMessageDialog(this, "Значение 'Объем двигателя' должно быть положительным!");
            return;
        }
        try {
            taxVal = Float.valueOf(tax.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Значение 'Сумма налога' должно быть числом!");
            return;
        }
        try {
            massVal = Float.valueOf(mass.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Значение 'Масса' должно быть числом!");
            return;
        }
        if(massVal <= 0) {
            JOptionPane.showMessageDialog(this, "Значение 'Масса' должно быть положительным!");
            return;
        }
        try {
            mileageVal = Float.valueOf(mileage.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Значение 'Пробег' должно быть числом!");
            return;
        }
        if(mileageVal < 0) {
            JOptionPane.showMessageDialog(this, "Значение 'Пробег' должно быть положительным!");
            return;
        }
        inputDataController.setCarInfo(
                    brand.getSelectedIndex(),
                    model.getSelectedIndex(),
                    body.getSelectedIndex(),
                    yearVal,
                    volumeVal,
                    region.getSelectedIndex(),
                    taxVal,
                    massVal,
                    mileageVal
                );
        controller.changeFrame("usageConditions");
    }//GEN-LAST:event_nextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox body;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JComboBox brand;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField mass;
    private javax.swing.JLabel massLabel;
    private javax.swing.JTextField mileage;
    private javax.swing.JLabel mileageLable;
    private javax.swing.JComboBox model;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JButton next;
    private javax.swing.JComboBox region;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JTextField tax;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField volume;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField year;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
