/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import auto.InputDataController;
import auto.Pair;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author gorz
 */
public class Components extends javax.swing.JFrame implements Clearable{

    private GuiController controller;
    private InputDataController inputDataController;
    private ArrayList<Pair<Integer, Integer>> selectedComponents;
    private ArrayList<Pair<Integer, Integer>> selectedEquipments;
    private ArrayList<String> componentsNames = null;
    private ArrayList<String> equipmentsNames = null;
    private ArrayList<EqPanel> panelsComponents = null;
    private ArrayList<EqPanel> panelsEquipments = null;
    private boolean needUpdate = true;
    /**
     * Creates new form Components
     */
    public Components(GuiController controller, InputDataController inputDataController) {
        initComponents();
        this.controller = controller;
        this.inputDataController = inputDataController;
        selectedComponents = new ArrayList<Pair<Integer, Integer>>();
        selectedEquipments = new ArrayList<Pair<Integer, Integer>>();
        panelsComponents = new ArrayList<EqPanel>();
        panelsEquipments = new ArrayList<EqPanel>();
        components.setLayout(new BoxLayout(components, BoxLayout.Y_AXIS));
        equipments.setLayout(new BoxLayout(equipments, BoxLayout.Y_AXIS));                
        //this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listOfComponents = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        components = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        listOfEquipments = new javax.swing.JComboBox();
        addEquipment = new javax.swing.JButton();
        addComponent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipments = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Компоненты и оборудование");

        javax.swing.GroupLayout componentsLayout = new javax.swing.GroupLayout(components);
        components.setLayout(componentsLayout);
        componentsLayout.setHorizontalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        componentsLayout.setVerticalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(components);

        jLabel2.setText("Компоненты:");

        jLabel3.setText("Оборудование:");

        addEquipment.setText("Добавить");
        addEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEquipmentActionPerformed(evt);
            }
        });

        addComponent.setText("Добавить");
        addComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComponentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipmentsLayout = new javax.swing.GroupLayout(equipments);
        equipments.setLayout(equipmentsLayout);
        equipmentsLayout.setHorizontalGroup(
            equipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        equipmentsLayout.setVerticalGroup(
            equipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(equipments);

        back.setText("Назад");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setText("Продолжить");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listOfComponents, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addComponent))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listOfEquipments, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addEquipment))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listOfComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addComponent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listOfEquipments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEquipment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(next))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void clear() {
        needUpdate = true;
        listOfComponents.removeAllItems();
        listOfEquipments.removeAllItems();
        selectedComponents.clear();
        selectedEquipments.clear();
        panelsComponents.clear();
        panelsEquipments.clear();
        components.removeAll();
        equipments.removeAll();
    }
    
    private void addComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComponentActionPerformed
        int index = listOfComponents.getSelectedIndex();
        selectedComponents.add(new Pair(index, 1));
        EqPanel panel = new EqPanel(componentsNames.get(index));
        panel.setAlignmentX(LEFT_ALIGNMENT);
        panelsComponents.add(panel);
        components.add(panel);
        components.revalidate();
    }//GEN-LAST:event_addComponentActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        for(int i = 0; i<selectedEquipments.size(); i++) {
            selectedEquipments.get(i).second = panelsEquipments.get(i).getCount();
        }
        for(int i = 0; i<selectedComponents.size(); i++) {
            selectedComponents.get(i).second = panelsComponents.get(i).getCount();
        }
        inputDataController.setComponentsAndEquipments(
                selectedComponents, 
                selectedEquipments);
        controller.changeFrame("repair");
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.changeFrame("usageConditions");
    }//GEN-LAST:event_backActionPerformed

    private void addEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipmentActionPerformed
        int index = listOfEquipments.getSelectedIndex();
        selectedEquipments.add(new Pair(index, 1));
        EqPanel panel = new EqPanel(equipmentsNames.get(index));
        panel.setAlignmentX(LEFT_ALIGNMENT);
        panelsEquipments.add(panel);
        equipments.add(panel);
        equipments.revalidate();
    }//GEN-LAST:event_addEquipmentActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(needUpdate) {
            componentsNames = inputDataController.getComponents();
            for(String name : componentsNames) {
                listOfComponents.addItem(name);
            }
            equipmentsNames = inputDataController.getEquipments();
            for(String name : equipmentsNames) {
                listOfEquipments.addItem(name);
            }   
            needUpdate = false;
        }
    }//GEN-LAST:event_formComponentShown

    class EqPanel extends JPanel {
        JTextField count;
        JLabel name;
        
        public EqPanel(String n) {
            count = new JTextField("1", 5);
            name = new JLabel(n);
            setLayout(new FlowLayout(FlowLayout.LEADING));
            add(count);
            add(name);
            setMaximumSize(getPreferredSize());
        }
        
        public int getCount() {
            return Integer.valueOf(count.getText());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComponent;
    private javax.swing.JButton addEquipment;
    private javax.swing.JButton back;
    private javax.swing.JPanel components;
    private javax.swing.JPanel equipments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox listOfComponents;
    private javax.swing.JComboBox listOfEquipments;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
