/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import auto.InputDataController;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author gorz
 */
public class UsageConditions extends javax.swing.JFrame implements Clearable {

    
    private GuiController controller;
    private InputDataController inputDataController;
    private ArrayList<JCheckBox> usageConditionChecks;
    private ArrayList<JCheckBox> damageChecks;
    /**
     * Creates new form UsageConditions
     */
    public UsageConditions(GuiController controller, InputDataController inputDataController) {
        initComponents();
        this.controller = controller;
        this.inputDataController = inputDataController;
        usageConditionChecks = new ArrayList<JCheckBox>();
        ArrayList<String> usageConditionsNames = inputDataController.getUsageConditions();
        usageConditions.setLayout(new BoxLayout(usageConditions, BoxLayout.Y_AXIS));
        for(String n : usageConditionsNames) {
            JCheckBox box = new JCheckBox(n);
            box.setAlignmentX(LEFT_ALIGNMENT);
            usageConditions.add(box);
            usageConditionChecks.add(box);
        }
        damageChecks = new ArrayList<JCheckBox>();
        ArrayList<String> damagesNames = inputDataController.getDamages();
        damages.setLayout(new BoxLayout(damages, BoxLayout.Y_AXIS));
        for(String n : damagesNames) {
            JCheckBox box = new JCheckBox(n);
            box.setAlignmentX(LEFT_ALIGNMENT);
            damages.add(box);
            damageChecks.add(box);
        }
        back.addKeyListener(GuiController.listener);
        next.addKeyListener(GuiController.listener);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usageConditions = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        damages = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Условия испольщования");

        javax.swing.GroupLayout usageConditionsLayout = new javax.swing.GroupLayout(usageConditions);
        usageConditions.setLayout(usageConditionsLayout);
        usageConditionsLayout.setHorizontalGroup(
            usageConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        usageConditionsLayout.setVerticalGroup(
            usageConditionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(usageConditions);

        javax.swing.GroupLayout damagesLayout = new javax.swing.GroupLayout(damages);
        damages.setLayout(damagesLayout);
        damagesLayout.setHorizontalGroup(
            damagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        damagesLayout.setVerticalGroup(
            damagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(damages);

        jLabel2.setText("Дефекты кузова:");

        jLabel3.setText("Условия хранения и эксплотации");

        back.setText("Назад");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setText("Продолжить");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(next))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void clear() {
        for(JCheckBox c : usageConditionChecks) {
            c.setSelected(false);
        }
        for(JCheckBox c : damageChecks) {
            c.setSelected(false);
        }
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        controller.changeFrame("carInfo");
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        ArrayList<Boolean> usageConditionsSelections = new ArrayList<Boolean>();
        for(JCheckBox c : usageConditionChecks) {
            usageConditionsSelections.add(c.isSelected());
        }
        ArrayList<Boolean> damagesSelections = new ArrayList<Boolean>();
        for(JCheckBox c : damageChecks) {
            damagesSelections.add(c.isSelected());
        }
        inputDataController.setUsageConditions(
                usageConditionsSelections, 
                damagesSelections
        );
        /*float f = inputDataController.getUsageConditionsFactor(
                inputDataController.year, 
                usageConditionsSelections,
                damagesSelections);
        JOptionPane.showMessageDialog(this, "Дз: "+f);*/
        controller.changeFrame("components");
    }//GEN-LAST:event_nextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel damages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton next;
    private javax.swing.JPanel usageConditions;
    // End of variables declaration//GEN-END:variables
}
